version: '3'
services:

  postgres:
    image: 'postgres:9.6-alpine'
    volumes:
      - postgres-email-volume:/var/lib/postgresql/email
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: email123
      POSTGRES_DB: email
      POSTGRES_HOST: postgres

volumes:
  postgres-email-volume: