
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: transacoes-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    topic: transacoes
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
