spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: mygroupid
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: "false"
    topic:
      pagamento: ${KAFKA_TOPIC:pagamento}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5433/email}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:email123}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    description: '@project.description@'

server:
  port : 8081
